/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

/**
 *
 * @author Beast
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        super.setTitle("Ship Shinker 2017");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        I1 = new javax.swing.JButton();
        J1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        J2 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        I2 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        J3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        I3 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        J4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        I4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        I5 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        J5 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        I6 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        J6 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        J7 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        I7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        J8 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        I8 = new javax.swing.JButton();
        G9 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        F9 = new javax.swing.JButton();
        J9 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        H9 = new javax.swing.JButton();
        E9 = new javax.swing.JButton();
        D9 = new javax.swing.JButton();
        I9 = new javax.swing.JButton();
        E10 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        I10 = new javax.swing.JButton();
        J10 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        F10 = new javax.swing.JButton();
        G10 = new javax.swing.JButton();
        H10 = new javax.swing.JButton();
        alphabethLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A1.setMaximumSize(new java.awt.Dimension(50, 50));
        A1.setMinimumSize(new java.awt.Dimension(50, 50));
        A1.setPreferredSize(new java.awt.Dimension(20, 20));
        A1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A2.setMaximumSize(new java.awt.Dimension(50, 50));
        A2.setMinimumSize(new java.awt.Dimension(50, 50));
        A2.setPreferredSize(new java.awt.Dimension(20, 20));
        A2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A3.setMaximumSize(new java.awt.Dimension(50, 50));
        A3.setMinimumSize(new java.awt.Dimension(50, 50));
        A3.setPreferredSize(new java.awt.Dimension(20, 20));
        A3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A4.setMaximumSize(new java.awt.Dimension(50, 50));
        A4.setMinimumSize(new java.awt.Dimension(50, 50));
        A4.setPreferredSize(new java.awt.Dimension(20, 20));
        A4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A5.setMaximumSize(new java.awt.Dimension(50, 50));
        A5.setMinimumSize(new java.awt.Dimension(50, 50));
        A5.setPreferredSize(new java.awt.Dimension(20, 20));
        A5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A6.setMaximumSize(new java.awt.Dimension(50, 50));
        A6.setMinimumSize(new java.awt.Dimension(50, 50));
        A6.setPreferredSize(new java.awt.Dimension(20, 20));
        A6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A7.setMaximumSize(new java.awt.Dimension(50, 50));
        A7.setMinimumSize(new java.awt.Dimension(50, 50));
        A7.setPreferredSize(new java.awt.Dimension(20, 20));
        A7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A8.setMaximumSize(new java.awt.Dimension(50, 50));
        A8.setMinimumSize(new java.awt.Dimension(50, 50));
        A8.setPreferredSize(new java.awt.Dimension(20, 20));
        A8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A9.setMaximumSize(new java.awt.Dimension(50, 50));
        A9.setMinimumSize(new java.awt.Dimension(50, 50));
        A9.setPreferredSize(new java.awt.Dimension(20, 20));
        A9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        A10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A10.setMaximumSize(new java.awt.Dimension(50, 50));
        A10.setMinimumSize(new java.awt.Dimension(50, 50));
        A10.setPreferredSize(new java.awt.Dimension(20, 20));
        A10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B1.setMaximumSize(new java.awt.Dimension(50, 50));
        B1.setMinimumSize(new java.awt.Dimension(50, 50));
        B1.setPreferredSize(new java.awt.Dimension(20, 20));
        B1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        C1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C1.setMaximumSize(new java.awt.Dimension(50, 50));
        C1.setMinimumSize(new java.awt.Dimension(50, 50));
        C1.setPreferredSize(new java.awt.Dimension(20, 20));
        C1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D1.setMaximumSize(new java.awt.Dimension(50, 50));
        D1.setMinimumSize(new java.awt.Dimension(50, 50));
        D1.setPreferredSize(new java.awt.Dimension(20, 20));
        D1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E1.setMaximumSize(new java.awt.Dimension(50, 50));
        E1.setMinimumSize(new java.awt.Dimension(50, 50));
        E1.setPreferredSize(new java.awt.Dimension(20, 20));
        E1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F1.setMaximumSize(new java.awt.Dimension(50, 50));
        F1.setMinimumSize(new java.awt.Dimension(50, 50));
        F1.setPreferredSize(new java.awt.Dimension(20, 20));
        F1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G1.setMaximumSize(new java.awt.Dimension(50, 50));
        G1.setMinimumSize(new java.awt.Dimension(50, 50));
        G1.setPreferredSize(new java.awt.Dimension(20, 20));
        G1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H1.setMaximumSize(new java.awt.Dimension(50, 50));
        H1.setMinimumSize(new java.awt.Dimension(50, 50));
        H1.setPreferredSize(new java.awt.Dimension(20, 20));
        H1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I1.setMaximumSize(new java.awt.Dimension(50, 50));
        I1.setMinimumSize(new java.awt.Dimension(50, 50));
        I1.setPreferredSize(new java.awt.Dimension(20, 20));
        I1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J1.setMaximumSize(new java.awt.Dimension(50, 50));
        J1.setMinimumSize(new java.awt.Dimension(50, 50));
        J1.setPreferredSize(new java.awt.Dimension(20, 20));
        J1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C2.setMaximumSize(new java.awt.Dimension(50, 50));
        C2.setMinimumSize(new java.awt.Dimension(50, 50));
        C2.setPreferredSize(new java.awt.Dimension(20, 20));
        C2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F2.setMaximumSize(new java.awt.Dimension(50, 50));
        F2.setMinimumSize(new java.awt.Dimension(50, 50));
        F2.setPreferredSize(new java.awt.Dimension(20, 20));
        F2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D2.setMaximumSize(new java.awt.Dimension(50, 50));
        D2.setMinimumSize(new java.awt.Dimension(50, 50));
        D2.setPreferredSize(new java.awt.Dimension(20, 20));
        D2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E2.setMaximumSize(new java.awt.Dimension(50, 50));
        E2.setMinimumSize(new java.awt.Dimension(50, 50));
        E2.setPreferredSize(new java.awt.Dimension(20, 20));
        E2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J2.setMaximumSize(new java.awt.Dimension(50, 50));
        J2.setMinimumSize(new java.awt.Dimension(50, 50));
        J2.setPreferredSize(new java.awt.Dimension(20, 20));
        J2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G2.setMaximumSize(new java.awt.Dimension(50, 50));
        G2.setMinimumSize(new java.awt.Dimension(50, 50));
        G2.setPreferredSize(new java.awt.Dimension(20, 20));
        G2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H2.setMaximumSize(new java.awt.Dimension(50, 50));
        H2.setMinimumSize(new java.awt.Dimension(50, 50));
        H2.setPreferredSize(new java.awt.Dimension(20, 20));
        H2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I2.setMaximumSize(new java.awt.Dimension(50, 50));
        I2.setMinimumSize(new java.awt.Dimension(50, 50));
        I2.setPreferredSize(new java.awt.Dimension(20, 20));
        I2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B2.setMaximumSize(new java.awt.Dimension(50, 50));
        B2.setMinimumSize(new java.awt.Dimension(50, 50));
        B2.setPreferredSize(new java.awt.Dimension(20, 20));
        B2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J3.setMaximumSize(new java.awt.Dimension(50, 50));
        J3.setMinimumSize(new java.awt.Dimension(50, 50));
        J3.setPreferredSize(new java.awt.Dimension(20, 20));
        J3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F3.setMaximumSize(new java.awt.Dimension(50, 50));
        F3.setMinimumSize(new java.awt.Dimension(50, 50));
        F3.setPreferredSize(new java.awt.Dimension(20, 20));
        F3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E3.setMaximumSize(new java.awt.Dimension(50, 50));
        E3.setMinimumSize(new java.awt.Dimension(50, 50));
        E3.setPreferredSize(new java.awt.Dimension(20, 20));
        E3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G3.setMaximumSize(new java.awt.Dimension(50, 50));
        G3.setMinimumSize(new java.awt.Dimension(50, 50));
        G3.setPreferredSize(new java.awt.Dimension(20, 20));
        G3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I3.setMaximumSize(new java.awt.Dimension(50, 50));
        I3.setMinimumSize(new java.awt.Dimension(50, 50));
        I3.setPreferredSize(new java.awt.Dimension(20, 20));
        I3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H3.setMaximumSize(new java.awt.Dimension(50, 50));
        H3.setMinimumSize(new java.awt.Dimension(50, 50));
        H3.setPreferredSize(new java.awt.Dimension(20, 20));
        H3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B3.setMaximumSize(new java.awt.Dimension(50, 50));
        B3.setMinimumSize(new java.awt.Dimension(50, 50));
        B3.setPreferredSize(new java.awt.Dimension(20, 20));
        B3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D3.setMaximumSize(new java.awt.Dimension(50, 50));
        D3.setMinimumSize(new java.awt.Dimension(50, 50));
        D3.setPreferredSize(new java.awt.Dimension(20, 20));
        D3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C3.setMaximumSize(new java.awt.Dimension(50, 50));
        C3.setMinimumSize(new java.awt.Dimension(50, 50));
        C3.setPreferredSize(new java.awt.Dimension(20, 20));
        C3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D4.setMaximumSize(new java.awt.Dimension(50, 50));
        D4.setMinimumSize(new java.awt.Dimension(50, 50));
        D4.setPreferredSize(new java.awt.Dimension(20, 20));
        D4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C4.setMaximumSize(new java.awt.Dimension(50, 50));
        C4.setMinimumSize(new java.awt.Dimension(50, 50));
        C4.setPreferredSize(new java.awt.Dimension(20, 20));
        C4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G4.setMaximumSize(new java.awt.Dimension(50, 50));
        G4.setMinimumSize(new java.awt.Dimension(50, 50));
        G4.setPreferredSize(new java.awt.Dimension(20, 20));
        G4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J4.setMaximumSize(new java.awt.Dimension(50, 50));
        J4.setMinimumSize(new java.awt.Dimension(50, 50));
        J4.setPreferredSize(new java.awt.Dimension(20, 20));
        J4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E4.setMaximumSize(new java.awt.Dimension(50, 50));
        E4.setMinimumSize(new java.awt.Dimension(50, 50));
        E4.setPreferredSize(new java.awt.Dimension(20, 20));
        E4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B4.setMaximumSize(new java.awt.Dimension(50, 50));
        B4.setMinimumSize(new java.awt.Dimension(50, 50));
        B4.setPreferredSize(new java.awt.Dimension(20, 20));
        B4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H4.setMaximumSize(new java.awt.Dimension(50, 50));
        H4.setMinimumSize(new java.awt.Dimension(50, 50));
        H4.setPreferredSize(new java.awt.Dimension(20, 20));
        H4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F4.setMaximumSize(new java.awt.Dimension(50, 50));
        F4.setMinimumSize(new java.awt.Dimension(50, 50));
        F4.setPreferredSize(new java.awt.Dimension(20, 20));
        F4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I4.setMaximumSize(new java.awt.Dimension(50, 50));
        I4.setMinimumSize(new java.awt.Dimension(50, 50));
        I4.setPreferredSize(new java.awt.Dimension(20, 20));
        I4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F5.setMaximumSize(new java.awt.Dimension(50, 50));
        F5.setMinimumSize(new java.awt.Dimension(50, 50));
        F5.setPreferredSize(new java.awt.Dimension(20, 20));
        F5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G5.setMaximumSize(new java.awt.Dimension(50, 50));
        G5.setMinimumSize(new java.awt.Dimension(50, 50));
        G5.setPreferredSize(new java.awt.Dimension(20, 20));
        G5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I5.setMaximumSize(new java.awt.Dimension(50, 50));
        I5.setMinimumSize(new java.awt.Dimension(50, 50));
        I5.setPreferredSize(new java.awt.Dimension(20, 20));
        I5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H5.setMaximumSize(new java.awt.Dimension(50, 50));
        H5.setMinimumSize(new java.awt.Dimension(50, 50));
        H5.setPreferredSize(new java.awt.Dimension(20, 20));
        H5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E5.setMaximumSize(new java.awt.Dimension(50, 50));
        E5.setMinimumSize(new java.awt.Dimension(50, 50));
        E5.setPreferredSize(new java.awt.Dimension(20, 20));
        E5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D5.setMaximumSize(new java.awt.Dimension(50, 50));
        D5.setMinimumSize(new java.awt.Dimension(50, 50));
        D5.setPreferredSize(new java.awt.Dimension(20, 20));
        D5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J5.setMaximumSize(new java.awt.Dimension(50, 50));
        J5.setMinimumSize(new java.awt.Dimension(50, 50));
        J5.setPreferredSize(new java.awt.Dimension(20, 20));
        J5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B5.setMaximumSize(new java.awt.Dimension(50, 50));
        B5.setMinimumSize(new java.awt.Dimension(50, 50));
        B5.setPreferredSize(new java.awt.Dimension(20, 20));
        B5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C5.setMaximumSize(new java.awt.Dimension(50, 50));
        C5.setMinimumSize(new java.awt.Dimension(50, 50));
        C5.setPreferredSize(new java.awt.Dimension(20, 20));
        C5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I6.setMaximumSize(new java.awt.Dimension(50, 50));
        I6.setMinimumSize(new java.awt.Dimension(50, 50));
        I6.setPreferredSize(new java.awt.Dimension(20, 20));
        I6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G6.setMaximumSize(new java.awt.Dimension(50, 50));
        G6.setMinimumSize(new java.awt.Dimension(50, 50));
        G6.setPreferredSize(new java.awt.Dimension(20, 20));
        G6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F6.setMaximumSize(new java.awt.Dimension(50, 50));
        F6.setMinimumSize(new java.awt.Dimension(50, 50));
        F6.setPreferredSize(new java.awt.Dimension(20, 20));
        F6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D6.setMaximumSize(new java.awt.Dimension(50, 50));
        D6.setMinimumSize(new java.awt.Dimension(50, 50));
        D6.setPreferredSize(new java.awt.Dimension(20, 20));
        D6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H6.setMaximumSize(new java.awt.Dimension(50, 50));
        H6.setMinimumSize(new java.awt.Dimension(50, 50));
        H6.setPreferredSize(new java.awt.Dimension(20, 20));
        H6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B6.setMaximumSize(new java.awt.Dimension(50, 50));
        B6.setMinimumSize(new java.awt.Dimension(50, 50));
        B6.setPreferredSize(new java.awt.Dimension(20, 20));
        B6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J6.setMaximumSize(new java.awt.Dimension(50, 50));
        J6.setMinimumSize(new java.awt.Dimension(50, 50));
        J6.setPreferredSize(new java.awt.Dimension(20, 20));
        J6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E6.setMaximumSize(new java.awt.Dimension(50, 50));
        E6.setMinimumSize(new java.awt.Dimension(50, 50));
        E6.setPreferredSize(new java.awt.Dimension(20, 20));
        E6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C6.setMaximumSize(new java.awt.Dimension(50, 50));
        C6.setMinimumSize(new java.awt.Dimension(50, 50));
        C6.setPreferredSize(new java.awt.Dimension(20, 20));
        C6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J7.setMaximumSize(new java.awt.Dimension(50, 50));
        J7.setMinimumSize(new java.awt.Dimension(50, 50));
        J7.setPreferredSize(new java.awt.Dimension(20, 20));
        J7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H7.setMaximumSize(new java.awt.Dimension(50, 50));
        H7.setMinimumSize(new java.awt.Dimension(50, 50));
        H7.setPreferredSize(new java.awt.Dimension(20, 20));
        H7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G7.setMaximumSize(new java.awt.Dimension(50, 50));
        G7.setMinimumSize(new java.awt.Dimension(50, 50));
        G7.setPreferredSize(new java.awt.Dimension(20, 20));
        G7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E7.setMaximumSize(new java.awt.Dimension(50, 50));
        E7.setMinimumSize(new java.awt.Dimension(50, 50));
        E7.setPreferredSize(new java.awt.Dimension(20, 20));
        E7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B7.setMaximumSize(new java.awt.Dimension(50, 50));
        B7.setMinimumSize(new java.awt.Dimension(50, 50));
        B7.setPreferredSize(new java.awt.Dimension(20, 20));
        B7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I7.setMaximumSize(new java.awt.Dimension(50, 50));
        I7.setMinimumSize(new java.awt.Dimension(50, 50));
        I7.setPreferredSize(new java.awt.Dimension(20, 20));
        I7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D7.setMaximumSize(new java.awt.Dimension(50, 50));
        D7.setMinimumSize(new java.awt.Dimension(50, 50));
        D7.setPreferredSize(new java.awt.Dimension(20, 20));
        D7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C7.setMaximumSize(new java.awt.Dimension(50, 50));
        C7.setMinimumSize(new java.awt.Dimension(50, 50));
        C7.setPreferredSize(new java.awt.Dimension(20, 20));
        C7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F7.setMaximumSize(new java.awt.Dimension(50, 50));
        F7.setMinimumSize(new java.awt.Dimension(50, 50));
        F7.setPreferredSize(new java.awt.Dimension(20, 20));
        F7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D8.setMaximumSize(new java.awt.Dimension(50, 50));
        D8.setMinimumSize(new java.awt.Dimension(50, 50));
        D8.setPreferredSize(new java.awt.Dimension(20, 20));
        D8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C8.setMaximumSize(new java.awt.Dimension(50, 50));
        C8.setMinimumSize(new java.awt.Dimension(50, 50));
        C8.setPreferredSize(new java.awt.Dimension(20, 20));
        C8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F8.setMaximumSize(new java.awt.Dimension(50, 50));
        F8.setMinimumSize(new java.awt.Dimension(50, 50));
        F8.setPreferredSize(new java.awt.Dimension(20, 20));
        F8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J8.setMaximumSize(new java.awt.Dimension(50, 50));
        J8.setMinimumSize(new java.awt.Dimension(50, 50));
        J8.setPreferredSize(new java.awt.Dimension(20, 20));
        J8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H8.setMaximumSize(new java.awt.Dimension(50, 50));
        H8.setMinimumSize(new java.awt.Dimension(50, 50));
        H8.setPreferredSize(new java.awt.Dimension(20, 20));
        H8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G8.setMaximumSize(new java.awt.Dimension(50, 50));
        G8.setMinimumSize(new java.awt.Dimension(50, 50));
        G8.setPreferredSize(new java.awt.Dimension(20, 20));
        G8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E8.setMaximumSize(new java.awt.Dimension(50, 50));
        E8.setMinimumSize(new java.awt.Dimension(50, 50));
        E8.setPreferredSize(new java.awt.Dimension(20, 20));
        E8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B8.setMaximumSize(new java.awt.Dimension(50, 50));
        B8.setMinimumSize(new java.awt.Dimension(50, 50));
        B8.setPreferredSize(new java.awt.Dimension(20, 20));
        B8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I8.setMaximumSize(new java.awt.Dimension(50, 50));
        I8.setMinimumSize(new java.awt.Dimension(50, 50));
        I8.setPreferredSize(new java.awt.Dimension(20, 20));
        I8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G9.setMaximumSize(new java.awt.Dimension(50, 50));
        G9.setMinimumSize(new java.awt.Dimension(50, 50));
        G9.setPreferredSize(new java.awt.Dimension(20, 20));
        G9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C9.setMaximumSize(new java.awt.Dimension(50, 50));
        C9.setMinimumSize(new java.awt.Dimension(50, 50));
        C9.setPreferredSize(new java.awt.Dimension(20, 20));
        C9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F9.setMaximumSize(new java.awt.Dimension(50, 50));
        F9.setMinimumSize(new java.awt.Dimension(50, 50));
        F9.setPreferredSize(new java.awt.Dimension(20, 20));
        F9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J9.setMaximumSize(new java.awt.Dimension(50, 50));
        J9.setMinimumSize(new java.awt.Dimension(50, 50));
        J9.setPreferredSize(new java.awt.Dimension(20, 20));
        J9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B9.setMaximumSize(new java.awt.Dimension(50, 50));
        B9.setMinimumSize(new java.awt.Dimension(50, 50));
        B9.setPreferredSize(new java.awt.Dimension(20, 20));
        B9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H9.setMaximumSize(new java.awt.Dimension(50, 50));
        H9.setMinimumSize(new java.awt.Dimension(50, 50));
        H9.setPreferredSize(new java.awt.Dimension(20, 20));
        H9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E9.setMaximumSize(new java.awt.Dimension(50, 50));
        E9.setMinimumSize(new java.awt.Dimension(50, 50));
        E9.setPreferredSize(new java.awt.Dimension(20, 20));
        E9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D9.setMaximumSize(new java.awt.Dimension(50, 50));
        D9.setMinimumSize(new java.awt.Dimension(50, 50));
        D9.setPreferredSize(new java.awt.Dimension(20, 20));
        D9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I9.setMaximumSize(new java.awt.Dimension(50, 50));
        I9.setMinimumSize(new java.awt.Dimension(50, 50));
        I9.setPreferredSize(new java.awt.Dimension(20, 20));
        I9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        E10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E10.setMaximumSize(new java.awt.Dimension(50, 50));
        E10.setMinimumSize(new java.awt.Dimension(50, 50));
        E10.setPreferredSize(new java.awt.Dimension(20, 20));
        E10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        C10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C10.setMaximumSize(new java.awt.Dimension(50, 50));
        C10.setMinimumSize(new java.awt.Dimension(50, 50));
        C10.setPreferredSize(new java.awt.Dimension(20, 20));
        C10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        D10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D10.setMaximumSize(new java.awt.Dimension(50, 50));
        D10.setMinimumSize(new java.awt.Dimension(50, 50));
        D10.setPreferredSize(new java.awt.Dimension(20, 20));
        D10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        I10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        I10.setMaximumSize(new java.awt.Dimension(50, 50));
        I10.setMinimumSize(new java.awt.Dimension(50, 50));
        I10.setPreferredSize(new java.awt.Dimension(20, 20));
        I10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        J10.setMaximumSize(new java.awt.Dimension(50, 50));
        J10.setMinimumSize(new java.awt.Dimension(50, 50));
        J10.setPreferredSize(new java.awt.Dimension(20, 20));
        J10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        B10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B10.setMaximumSize(new java.awt.Dimension(50, 50));
        B10.setMinimumSize(new java.awt.Dimension(50, 50));
        B10.setPreferredSize(new java.awt.Dimension(20, 20));
        B10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        F10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F10.setMaximumSize(new java.awt.Dimension(50, 50));
        F10.setMinimumSize(new java.awt.Dimension(50, 50));
        F10.setPreferredSize(new java.awt.Dimension(20, 20));
        F10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        G10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G10.setMaximumSize(new java.awt.Dimension(50, 50));
        G10.setMinimumSize(new java.awt.Dimension(50, 50));
        G10.setPreferredSize(new java.awt.Dimension(20, 20));
        G10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        H10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H10.setMaximumSize(new java.awt.Dimension(50, 50));
        H10.setMinimumSize(new java.awt.Dimension(50, 50));
        H10.setPreferredSize(new java.awt.Dimension(20, 20));
        H10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        alphabethLine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alphabethLine.setText(" A    B    C    D    E    F    G   H    I     J ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alphabethLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(alphabethLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton D1;
    private javax.swing.JButton D10;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton D9;
    private javax.swing.JButton E1;
    private javax.swing.JButton E10;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton E9;
    private javax.swing.JButton F1;
    private javax.swing.JButton F10;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton F9;
    private javax.swing.JButton G1;
    private javax.swing.JButton G10;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton G9;
    private javax.swing.JButton H1;
    private javax.swing.JButton H10;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JButton H9;
    private javax.swing.JButton I1;
    private javax.swing.JButton I10;
    private javax.swing.JButton I2;
    private javax.swing.JButton I3;
    private javax.swing.JButton I4;
    private javax.swing.JButton I5;
    private javax.swing.JButton I6;
    private javax.swing.JButton I7;
    private javax.swing.JButton I8;
    private javax.swing.JButton I9;
    private javax.swing.JButton J1;
    private javax.swing.JButton J10;
    private javax.swing.JButton J2;
    private javax.swing.JButton J3;
    private javax.swing.JButton J4;
    private javax.swing.JButton J5;
    private javax.swing.JButton J6;
    private javax.swing.JButton J7;
    private javax.swing.JButton J8;
    private javax.swing.JButton J9;
    private javax.swing.JLabel alphabethLine;
    // End of variables declaration//GEN-END:variables
}
